dist: trusty
language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # electron-builder => wine & it's deps
  # - wget https://dl.winehq.org/wine-builds/Release.key
  # - sudo apt-key add Release.key
  # - sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
  # - sudo apt-get update
  # - sudo apt-get install -y winehq-stable gcc
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - curl -L https://dl.winehq.org/wine-builds/Release.key > Release.key && sudo apt-key add Release.key && sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu'
  - sudo apt-get update
  # - sudo apt-get install -y libstdc++6-4.7-dev
  # - sudo apt-get install -y --no-install-recommends software-properties-common
  - sudo dpkg --add-architecture i386
  # - sudo apt-get update
  # - sudo apt-get -y purge software-properties-common libdbus-glib-1-2 python3-dbus python3-gi python3-pycurl python3-software-properties
  - sudo apt-get install -y --install-recommends winehq-devel g++-6
  # - sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* && sudo unlink Release.key

script:
  - yarn test -- --coverage
  - sonar-scanner
  - npm version patch -m "release v%s [skip ci]"
  - yarn run build
  - yarn run build:electron

addons:
  sonarcloud:
    organization: 'magoo-magoo-github'

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@travis-ci.org"
  - git config --global push.default matching
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git checkout -- .
  - git status
  - git push origin HEAD:$TRAVIS_BRANCH
  - git push --tags

deploy:
  - provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      branch: master
      tags: foo
